import mongoose, { Schema } from 'mongoose';


// Define profile schema
var profileSchema = new Schema({
  username: {
    type: String,
    unique: true,
  },
  name: String,
  admission_no: Number,
  dob: Date,
  class: String,
  section: String,
  address: String,
  contact: Number,
  pic: String,
  classes_tot: Number,
  classes_att: Number,
  classes_perc: Number,
  remarks: String,
  t1_s1: Number,
  t1_s2: Number,
  t1_s3: Number,
  t1_s4: Number,
  t1_s5: Number,
  t1_s6: Number,
  t1_tot:Number,
  t1_perc: Number,
  t2_s1: Number,
  t2_s2: Number,
  t2_s3: Number,
  t2_s4: Number,
  t2_s5: Number,
  t2_s6: Number,
  t2_tot:Number,
  t2_perc: Number,
   e1_s1: Number,
    e1_s2: Number,
    e1_s3: Number,
    e1_s4: Number,
    e1_s5: Number,
    e1_s6: Number,
    e1_tot:Number,
    e1_perc: Number,
    e2_s1: Number,
    e2_s2: Number,
    e2_s3: Number,
    e2_s4: Number,
    e2_s5: Number,
    e2_s6: Number,
    e2_tot:Number,
    e2_perc: Number,
  home_yday: String,
  home_tdy: String,
  fee_tot: Number,
  fee_paid:Number,
  fee_bal: Number,
  notes1: String,
  notes2: String,
  notes3: String,
  notes4: String,
  notes5: String,
  notes6: String,
});

// Export Mongoose model
export default mongoose.model('profile', profileSchema);